apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml -v convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: query-api
  name: query-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: query-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml -v convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/pipeline-default: "true"
        io.kompose.service: query-api
    spec:
      containers:
        - image: query_api
          name: query-api
          env:
            - name: WEATHER_API_KEY
              value: 3f6198c6cf3aeabb8dd13ab2645cebd2
            - name: KAFKA_BROKER
              value: kafka:29092
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
