apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml -v convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-caching
  name: redis_caching
spec:
  ports:
    - name: "82"
      port: 82
      targetPort: 82
  selector:
    io.kompose.service: redis-caching
status:
  loadBalancer: {}
