apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml -v convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-caching
  name: redis-caching
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-caching
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file compose.yaml -v convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/pipeline-default: "true"
        io.kompose.service: redis-caching
    spec:
      containers:
        - image: redis_caching
          name: redis-caching
          ports:
            - containerPort: 82
              hostPort: 82
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
